name: audio_trimmer_plus
description: A customizable Flutter widget for audio trimming UI with waveform visualization, trim handles, and playback controls.
version: 0.0.1
homepage: https://github.com/youseflabs-k/audio_trimmer_plus

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audio_waveforms: ^2.0.2
  ffmpeg_kit_flutter_new: ^4.1.0
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
